id: D20344A39
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-02-24T10:25:51+00:00'
last_modified: '2022-05-29T08:12:02.026781+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    '1998':
      image_group_id: I1PD95919
      title: རྣལ་འབྱོར་སྤྱོད་པའི་ས་རྣམ་པར་གཏན་ལ་དབབ་པ་བསྡུ་བ།
      total_pages: 1618
      order: 74
      base_file: 1998.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
