id: P0E7E2AF7
initial_creation_type: ocr
source_metadata:
  volumes:
    4d86c64b3486428f811c4dbe61852e70:
      base_file: v074.txt
      image_group_id: I1PD95919
      title: རྣལ་འབྱོར་སྤྱོད་པའི་ས་རྣམ་པར་གཏན་ལ་དབབ་པ་བསྡུ་བ།
      total_pages: 1618
      volume_number: 74
